using CloudStorage.FileService.Domain.FileManagement.ValueObjects;

namespace CloudStorage.FileService.Domain.FileManagement.Repositories.FileManagementOutboxRepository;

public record MarkProcessedModel(FileManagementOutboxId FileManagementOutboxId);
